# ansible/playbooks/setup.yml
---
- name: Configure DigitalOcean Droplet
  hosts: webservers
  gather_facts: true
  
  # Define variables for role paths
  vars:
    roles_base_path: "/mnt/workspace/source/ansible/roles"
    is_localhost: "{{ inventory_hostname == 'localhost' }}"
  
  pre_tasks:
    - name: Debug inventory information
      debug:
        msg:
          - "Inventory hostname: {{ inventory_hostname }}"
          - "Is localhost: {{ is_localhost }}"
          - "Ansible version: {{ ansible_version.full }}"
          - "Python interpreter: {{ ansible_python.executable }}"
    
    - name: Skip roles when running on localhost
      debug:
        msg: "Running on localhost. Will skip all roles to avoid errors."
      when: is_localhost
  
  # Use absolute paths for roles, but only when not on localhost
  roles:
    - { role: "{{ roles_base_path }}/common", when: "not is_localhost" }
    - { role: "{{ roles_base_path }}/docker", when: "not is_localhost" }
    - { role: "{{ roles_base_path }}/app", when: "not is_localhost" }
  
  tasks:
    - name: Dummy task for localhost
      debug:
        msg: "This is a dummy task that will run on localhost"
      when: is_localhost
    
    - name: Show success message
      debug:
        msg: "Playbook completed successfully"