# ansible/roles/docker/tasks/main.yml
---
# Docker is already installed by cloud-init in your template
# This role handles additional Docker configurations

- name: Create docker group if it doesn't exist
  group:
    name: docker
    state: present

- name: Add ansible user to docker group
  user:
    name: ansible
    groups: docker
    append: yes